satges: 
  -build
  -test

build website:
  stage: build
  image: node: 10.2.3
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifcats:
    paths:
      - ./public 

  test artifcat:
  script:
    -grep "Gatsby" ./public/index.html    
